# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main

# 본인이 설정한 값을 여기서 채워넣습니다.
# 리전, 버킷 이름, CodeDeploy 앱 이름, CodeDeploy 배포 그룹 이름
env:
  DOCKER_IMG_FULL_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${{ secrets.DOCKER_TAG }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # (1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # (2) JDK 11 세팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # properties 설정 파일 쓰기
      - name: make application.properties
        run: |
          echo ">> mkdir & touch"
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo ">> copy application.properties"
          echo "${{ secrets.APLICATION_PROPERTIES }}" >> ./application.properties

      # 권한 재설정
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      ## gradle build
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build


      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker build -t $DOCKER_IMG_FULL_NAME .
          docker push $DOCKER_IMG_FULL_NAME

        ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA,DOCKER_IMG_FULL_NAME
          script: |
            echo "run script..."
            ./deploy.sh
            echo "server run..."